package h2;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

@WebServlet(urlPatterns = "/CreateDBTable")
public class DatabaseInitServlet extends HttpServlet {

    @Override
    public void init() throws ServletException {
        // 데이터베이스 테이블 생성 (User, Schedule, Memo) (외래키는 없음)
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            // 기존 테이블 삭제
            stmt.execute("DROP TABLE IF EXISTS Memo");
            stmt.execute("DROP TABLE IF EXISTS Schedule");
            stmt.execute("DROP TABLE IF EXISTS Users");

            // 테이블 생성
            stmt.execute("CREATE TABLE IF NOT EXISTS Users (" +
                    "userId BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, " +
                    "username VARCHAR(255) NOT NULL, " +
                    "password VARCHAR(255) NOT NULL, " +
                    "email VARCHAR(255) NOT NULL " +
                    ")");
            stmt.execute("CREATE TABLE IF NOT EXISTS Schedule (" +
                    "ScheduleId BIGINT PRIMARY KEY AUTO_INCREMENT, " +
                    "S_content VARCHAR(255) NOT NULL, " +
                    "userId BIGINT NOT NULL " +
                    ")");
            stmt.execute("CREATE TABLE IF NOT EXISTS Memo (" +
                    "reviewId BIGINT PRIMARY KEY AUTO_INCREMENT, " +
                    "userId BIGINT NOT NULL, " +
                    "scheduleId BIGINT NOT NULL, " +
                    "M_content VARCHAR(255) NOT NULL " +
                    ")");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("text/html; charset=UTF-8");
        response.setCharacterEncoding("UTF-8");
        response.getWriter().write("테이블 생성 성공!");
    }
}